# Generated by Django 5.2.1 on 2025-06-01 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان پروژه با حداکثر ۱۰۰ کاراکتر برای شناسایی آسان', max_length=100)),
                ('description', models.TextField(help_text='توضیحات کامل درباره اهداف و جزئیات پروژه')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='تاریخ و زمان ایجاد پروژه، به صورت خودکار هنگام ساخت تنظیم می\u200cشود')),
                ('members', models.ManyToManyField(help_text='کاربرانی که به عنوان عضو در پروژه مشارکت دارند؛ هر کاربر می\u200cتواند در چندین پروژه عضو باشد', related_name='member_projects', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(help_text='کاربری که پروژه را ایجاد کرده و صاحب آن است؛ با حذف کاربر، پروژه حذف می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه\u200cها',
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='عنوان وظیفه با حداکثر ۱۰۰ کاراکتر برای شناسایی سریع', max_length=100)),
                ('description', models.TextField(help_text='توضیحات مفصل درباره کارهایی که باید برای این وظیفه انجام شود')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال انجام'), ('completed', 'تکمیل\u200cشده')], default='pending', help_text='وضعیت کنونی وظیفه: در انتظار، در حال انجام یا تکمیل\u200cشده', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'زیاد')], default='medium', help_text='سطح اولویت وظیفه: کم، متوسط یا زیاد', max_length=20)),
                ('deadline', models.DateTimeField(help_text='تاریخ و زمان مهلت برای تکمیل وظیفه')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='کاربری که وظیفه به او اختصاص داده شده؛ می\u200cتواند خالی باشد و با حذف کاربر، به null تنظیم می\u200cشود', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='پروژه\u200cای که این وظیفه به آن تعلق دارد؛ با حذف پروژه، وظیفه حذف می\u200cشود', on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='home.project')),
            ],
            options={
                'verbose_name': 'وظیفه',
                'verbose_name_plural': 'وظایف',
                'ordering': ['deadline'],
            },
        ),
    ]
