# Generated by Django 5.2.1 on 2025-06-02 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True, help_text='آخرین زمان ویرایش پروژه ، به صورت خودکار ثبت میشود'),
        ),
    ]
